module.exports = {
  card: require('./card'),
  coach: require('./coach'),
  curriculum: require('./curriculum'),
  grade: require('./grade'),
  group: require('./group'),
  participant: require('./participant'),
  program: require('./program'),
  record: require('./record'),
  registration: require('./registration'),
  scorecard: require('./scorecard'),
  session: require('./session'),
  stat: require('./stat'),
  user: require('./user'),
};
